sumodirjo/engineering-blogs

README.md

Changed Github's URL to the new engineering blog.

Changed Github's URL to the new engineering blog

---

README.md

They have a great selection of posts on here. Hard to find this blog too (tucked under Careers link), so maybe worth adding to this list.

Adds REA Group

---

README.md

Added Stylight Tech blog

---

README.md

Fix spelling of the introduction text.

docs(README.md) fix text spelling

---

README.md

Add Instacart Tech Blog

---

README.md

https://jollygoodcode.github.io/ from [Jolly Good Code](https://jollygoodcode.com/).

Add Jolly Good Code blog

---

README.md

Add cookpad.com's developer blog

---

README.md

Add Monsanto Engineering Blog

---

README.md

Added Flipkart, Myntra, Housing, Practo, Amazon, BookMyShow, Cleartrip engineering blogs.

Added Flipkart, Myntra, Housing, Practo, Amazon, BookMyShow, Cleartrip engineering blogs.

---

README.md

-Changed formatting to tables
-Updated Canva Blog misformatting

Table Formatting

---

README.md

This adds an entry to our company's new engineering blog.
In case you are interested, here is our latest blog post: [Protecting our mission-critical domain names](https://blendle.engineering/protecting-our-mission-critical-domain-names-e9807db9d84c).

Add Blendle Engineering

---

README.md

Added Mozilla's blog and changed the 'c' section so that it was alphabetical order.

Added Mozilla

---

README.md

add Peapod Engineering blog

---

README.md

Change Blablacar URL

---

README.md

Added ASOS.com Tech blog to the list

Added ASOS Tech Blog

---

README.md

Add world-class engineering team to the resources 😎

Add Showmax engineering blog to the resources.

---

README.md

the most recent PR seems to have broken the README formatting. Fixing it with this PR.

Fix README.md formatting (#1)

---

README.md

Adding [C.H. Robinson Engineering Blog](engineering.chrobinson.com) link :tada:

Add C.H. Robinson engineering blog

---

README.md

Add LoginRadius Engineering Blog

Add LoginRadius Engineering Blog

---

README.md

Added MojoAuth blog website link

Added MojoAuth 

---

README.md

added squadcast.com's site reliability engineering blog

Added Squadcast's SRE blog

---

README.md

https://www.datadoghq.com/blog/engineering/

Add Datadog engineering blog

---

README.md

Add Doordash Engineering Blog

---

README.md

Some nice content on ML engineering and mobile

Add snap eng blog

---

README.md

Fintech company, blog looks good

add affirm eng blog

---

README.md

add lyft eng blog

---

README.md

Adding [Whatnot's Eng blog](https://medium.com/whatnot-engineering). But what is [Whatnot](https://whatnot.com/)? Think Twitch meets eBay.
We're the [fastest growing marketplace of all time](https://znsrc.com/c/iexuryoimz) ([for 2 years in a row](https://znsrc.com/c/uhkwywkapb)) and we raised a $260M series D just this year from DST Global, A16z, YC, Bond Capital, and CapitalG at a $3.7B valuation.
Whatnot is perfectly positioned in the livestream shopping space, which is already big in China, as e-commerce continues to explode (Shopify + Amazon) in tandem with increased consumer video adoption (Youtube + TikTok).
Our tech blog at https://medium.com/whatnot-engineering details some of our technical components in how we're building our product. Attached are a couple example articles …

Add Whatnot Eng Blog.

---

README.md

Adds a newsletter that aggregates the latest engineering blog posts from tech companies.

Add "Big Tech Digest" newsletter in the tools section
